---
- hosts: Windows
  tasks:
  - name: Copy script from Ubuntu
    win_copy:
      src: /etc/ansible/playbook/script.ps1
      dest: C:\Users\whoami
  - name: RunScriptInPS
    win_shell: .\script.ps1

  - name: Delete script from Windows
    win_file:
      path: C:\Users\Name_user\script.ps1
      state: absent      

